interface WordPressExportOptions {
  companyName?: string;
  county?: string;
  reportType?: string;
  includeCharts?: boolean;
  includeDocuments?: boolean;
  includeNavigation?: boolean;
}

export function generateWordPressHTML(
  sections: any[],
  options: WordPressExportOptions = {}
): string {
  const { companyName, county, reportType, includeCharts = true, includeDocuments = true, includeNavigation = true } = options;

  const generateSectionHTML = (section: any) => {
    const sectionId = section.id.replace(/\s+/g, '-').toLowerCase();
    
    return `
<!-- wp:elementor/widget {"widgetType":"heading","id":"heading-${sectionId}","settings":{"_margin":{"unit":"px","top":"0","right":"0","bottom":"20","left":"0","isLinked":false},"_padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"title":"${section.title}","header_size":"h2","align":"left","text_color":"#1e3a8a","typography_typography":"custom","typography_font_size":{"unit":"px","size":28,"size_tablet":24,"size_mobile":20},"typography_font_weight":"700","_border_width":{"unit":"px","top":"0","right":"0","bottom":"2","left":"0","isLinked":false},"_border_color":"#e5e7eb","_border_radius":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false}},"elements":[],"isInner":false} /-->

<!-- wp:elementor/widget {"widgetType":"text-editor","id":"content-${sectionId}","settings":{"_margin":{"unit":"px","top":"0","right":"0","bottom":"30","left":"0","isLinked":false},"_padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"editor":"${section.content.replace(/"/g, '\\"').replace(/\n/g, '<br>')}","text_color":"#374151","typography_typography":"custom","typography_font_size":{"unit":"px","size":16,"size_tablet":15,"size_mobile":14},"typography_line_height":{"unit":"em","size":1.6,"size_tablet":1.5,"size_mobile":1.4},"_border_width":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"_border_color":"#e5e7eb","_border_radius":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false}},"elements":[],"isInner":false} /-->
    `;
  };

  const generateNavigationHTML = () => {
    if (!includeNavigation) return '';
    
    return `
<!-- wp:elementor/widget {"widgetType":"tabs","id":"report-navigation","settings":{"_margin":{"unit":"px","top":"0","right":"0","bottom":"30","left":"0","isLinked":false},"_padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"tabs":[${sections.map((section) => `{"tab_title":"${section.title}","tab_content":"<div id=\\"${section.id}\\" class=\\"report-section\\">${section.content.replace(/"/g, '\\"').replace(/\n/g, '<br>')}</div>"}`).join(',')}],"type":"horizontal","tabs_align_horizontal":"start","tabs_align_vertical":"stretch","_border_width":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"_border_color":"#e5e7eb","_border_radius":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false}},"elements":[],"isInner":false} /-->
    `;
  };

  const generateHeaderHTML = () => {
    return `
<!-- wp:elementor/widget {"widgetType":"heading","id":"report-header","settings":{"_margin":{"unit":"px","top":"0","right":"0","bottom":"30","left":"0","isLinked":false},"_padding":{"unit":"px","top":"20","right":"20","bottom":"20","left":"20","isLinked":false},"title":"${companyName ? `Bulldozer Company Profile: ${companyName}` : 'Research Report'}","header_size":"h1","align":"center","text_color":"#ffffff","background_color":"#1e3a8a","_border_width":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"_border_color":"#1e3a8a","_border_radius":{"unit":"px","top":"8","right":"8","bottom":"8","left":"8","isLinked":false}},"elements":[],"isInner":false} /-->

<!-- wp:elementor/widget {"widgetType":"text-editor","id":"report-meta","settings":{"_margin":{"unit":"px","top":"0","right":"0","bottom":"30","left":"0","isLinked":false},"_padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"editor":"<p style=\\"text-align: center; color: #6b7280;\\">${companyName ? `${companyName} • ${county} County • ${reportType}` : ''} • Generated by Local 825 Research • ${new Date().toLocaleDateString()}</p>","text_color":"#6b7280","typography_typography":"custom","typography_font_size":{"unit":"px","size":14,"size_tablet":13,"size_mobile":12},"typography_line_height":{"unit":"em","size":1.4,"size_tablet":1.3,"size_mobile":1.2},"_border_width":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"_border_color":"#e5e7eb","_border_radius":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false}},"elements":[],"isInner":false} /-->
    `;
  };

  const generateChartsHTML = () => {
    if (!includeCharts) return '';
    
    return `
<!-- wp:elementor/widget {"widgetType":"heading","id":"charts-section","settings":{"_margin":{"unit":"px","top":"40","right":"0","bottom":"20","left":"0","isLinked":false},"_padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"title":"Key Visualizations","header_size":"h2","align":"left","text_color":"#1e3a8a","typography_typography":"custom","typography_font_size":{"unit":"px","size":24,"size_tablet":22,"size_mobile":20},"typography_font_weight":"700","_border_width":{"unit":"px","top":"0","right":"0","bottom":"2","left":"0","isLinked":false},"_border_color":"#e5e7eb","_border_radius":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false}},"elements":[],"isInner":false} /-->

<!-- wp:elementor/widget {"widgetType":"image","id":"chart-placeholder","settings":{"_margin":{"unit":"px","top":"0","right":"0","bottom":"20","left":"0","isLinked":false},"_padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"image":{"url":"data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAwIiBoZWlnaHQ9IjQwMCIgdmlld0JveD0iMCAwIDYwMCA0MDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSI2MDAiIGhlaWdodD0iNDAwIiBmaWxsPSIjRjNGNEY2Ii8+Cjx0ZXh0IHg9IjMwMCIgeT0iMjAwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSIjNkI3MjgwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iMTYiPkNoYXJ0IHZpc3VhbGl6YXRpb248L3RleHQ+Cjwvc3ZnPgo=","id":0,"alt":"Chart Placeholder","title":"Chart Placeholder"},"_border_width":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"_border_color":"#e5e7eb","_border_radius":{"unit":"px","top":"8","right":"8","bottom":"8","left":"8","isLinked":false}},"elements":[],"isInner":false} /-->
    `;
  };

  const generateDocumentsHTML = () => {
    if (!includeDocuments) return '';
    
    return `
<!-- wp:elementor/widget {"widgetType":"heading","id":"documents-section","settings":{"_margin":{"unit":"px","top":"40","right":"0","bottom":"20","left":"0","isLinked":false},"_padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"title":"Supporting Documents","header_size":"h2","align":"left","text_color":"#1e3a8a","typography_typography":"custom","typography_font_size":{"unit":"px","size":24,"size_tablet":22,"size_mobile":20},"typography_font_weight":"700","_border_width":{"unit":"px","top":"0","right":"0","bottom":"2","left":"0","isLinked":false},"_border_color":"#e5e7eb","_border_radius":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false}},"elements":[],"isInner":false} /-->

<!-- wp:elementor/widget {"widgetType":"text-editor","id":"documents-list","settings":{"_margin":{"unit":"px","top":"0","right":"0","bottom":"30","left":"0","isLinked":false},"_padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"editor":"<ul style=\\"list-style: none; padding: 0;\\"><li style=\\"padding: 15px; margin-bottom: 10px; border: 1px solid #e5e7eb; border-radius: 8px; background-color: #f9fafb;\\"><strong>OSHA Violations Report</strong> - Recent safety violations and citations</li><li style=\\"padding: 15px; margin-bottom: 10px; border: 1px solid #e5e7eb; border-radius: 8px; background-color: #f9fafb;\\"><strong>Financial Statements</strong> - Company financial data and performance metrics</li><li style=\\"padding: 15px; margin-bottom: 10px; border: 1px solid #e5e7eb; border-radius: 8px; background-color: #f9fafb;\\"><strong>Project Portfolio</strong> - Current and completed projects list</li></ul>","text_color":"#374151","typography_typography":"custom","typography_font_size":{"unit":"px","size":16,"size_tablet":15,"size_mobile":14},"typography_line_height":{"unit":"em","size":1.6,"size_tablet":1.5,"size_mobile":1.4},"_border_width":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"_border_color":"#e5e7eb","_border_radius":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false}},"elements":[],"isInner":false} /-->
    `;
  };

  const generateFooterHTML = () => {
    return `
<!-- wp:elementor/widget {"widgetType":"text-editor","id":"report-footer","settings":{"_margin":{"unit":"px","top":"40","right":"0","bottom":"0","left":"0","isLinked":false},"_padding":{"unit":"px","top":"20","right":"20","bottom":"20","left":"20","isLinked":false},"editor":"<p style=\\"text-align: center; color: #6b7280; font-size: 14px; border-top: 1px solid #e5e7eb; padding-top: 20px;\\">Local 825 Research Platform • Confidential Report • Generated ${new Date().toLocaleDateString()}</p>","text_color":"#6b7280","typography_typography":"custom","typography_font_size":{"unit":"px","size":14,"size_tablet":13,"size_mobile":12},"typography_line_height":{"unit":"em","size":1.4,"size_tablet":1.3,"size_mobile":1.2},"_border_width":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"_border_color":"#e5e7eb","_border_radius":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false}},"elements":[],"isInner":false} /-->
    `;
  };

  return `
<!-- wp:elementor/section {"id":"report-container","settings":{"_margin":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"_padding":{"unit":"px","top":"40","right":"20","bottom":"40","left":"20","isLinked":false},"background_background_type":"classic","background_color":"#ffffff","_border_width":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"_border_color":"#e5e7eb","_border_radius":{"unit":"px","top":"12","right":"12","bottom":"12","left":"12","isLinked":false},"box_shadow_box_shadow_type":"yes","box_shadow_box_shadow":{"horizontal":0,"vertical":4,"blur":6,"spread":0,"color":"rgba(0,0,0,0.1)"}},"elements":[{"id":"report-column","elType":"column","settings":{"_column_size":100,"_inline_size":null,"_margin":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"_padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"_border_width":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"_border_color":"#e5e7eb","_border_radius":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false}},"elements":[],"isInner":false}],"isInner":false} -->

<!-- wp:elementor/column {"id":"report-column","settings":{"_column_size":100,"_inline_size":null,"_margin":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"_padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"_border_width":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false},"_border_color":"#e5e7eb","_border_radius":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":false}},"elements":[],"isInner":false} -->

${generateHeaderHTML()}

${includeNavigation ? generateNavigationHTML() : ''}

${sections.map(section => generateSectionHTML(section)).join('\n')}

${generateChartsHTML()}

${generateDocumentsHTML()}

${generateFooterHTML()}

<!-- /wp:elementor/column -->

<!-- /wp:elementor/section -->
  `;
}

export function generateWordPressCSS(): string {
  return `
/* Local 825 Report Styles */
.report-section {
  margin-bottom: 30px;
}

.report-section h2 {
  color: #1e3a8a;
  font-size: 24px;
  font-weight: 700;
  margin-bottom: 20px;
  border-bottom: 2px solid #e5e7eb;
  padding-bottom: 10px;
}

.report-section h3 {
  color: #374151;
  font-size: 20px;
  font-weight: 600;
  margin-bottom: 15px;
}

.report-section p {
  color: #374151;
  font-size: 16px;
  line-height: 1.6;
  margin-bottom: 15px;
}

.report-section ul, .report-section ol {
  color: #374151;
  font-size: 16px;
  line-height: 1.6;
  margin-bottom: 15px;
  padding-left: 20px;
}

.report-section li {
  margin-bottom: 8px;
}

.report-section strong {
  color: #1e3a8a;
  font-weight: 600;
}

.report-section a {
  color: #1e3a8a;
  text-decoration: underline;
}

.report-section a:hover {
  color: #1e40af;
}

/* Responsive Design */
@media (max-width: 768px) {
  .report-section h2 {
    font-size: 20px;
  }
  
  .report-section h3 {
    font-size: 18px;
  }
  
  .report-section p,
  .report-section ul,
  .report-section ol {
    font-size: 14px;
  }
}

/* Print Styles */
@media print {
  .report-section {
    page-break-inside: avoid;
  }
  
  .report-section h2 {
    page-break-after: avoid;
  }
}
  `;
}

export function generateWordPressJS(): string {
  return `
// Local 825 Report JavaScript
document.addEventListener('DOMContentLoaded', function() {
  // Smooth scrolling for anchor links
  const anchorLinks = document.querySelectorAll('a[href^="#"]');
  anchorLinks.forEach(link => {
    link.addEventListener('click', function(e) {
      e.preventDefault();
      const targetId = this.getAttribute('href').substring(1);
      const targetElement = document.getElementById(targetId);
      if (targetElement) {
        targetElement.scrollIntoView({
          behavior: 'smooth',
          block: 'start'
        });
      }
    });
  });

  // Initialize tooltips for document downloads
  const downloadButtons = document.querySelectorAll('.download-btn');
  downloadButtons.forEach(button => {
    button.addEventListener('click', function(e) {
      e.preventDefault();
      const fileName = this.getAttribute('data-file');
      // Handle download logic here
      console.log('Downloading:', fileName);
    });
  });

  // Chart initialization (if using Chart.js or similar)
  const chartContainers = document.querySelectorAll('.chart-container');
  chartContainers.forEach(container => {
    // Initialize charts here
    console.log('Initializing chart in:', container);
  });
});
  `;
} 